name: CI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
jobs:
  # tier 0: system-independent checks
  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: format
      run: ./hack/check-format.sh

  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout=15m0s --verbose

  build-ubuntu-2004:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17' ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      run: go test -v ./...

  build-windows-2019:
    runs-on: windows-2019
    strategy:
      matrix:
        go: [ '1.16' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        PCIDB_ENABLE_NETWORK_FETCH: "1"
      run: go test -v ./...

  build-macos-1015:
    runs-on: macos-10.15
    strategy:
      matrix:
        go: [ '1.16' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      run: go test -v ./...
